### ISSUE TITLE
Add tests and CI integration

### ISSUE THREAD

**Issue by peter279k** [RaggiTech/laravel-locatable#1]
As title, I think it should be good for this PHP package to add tests with PHPUnit and CI integration.

According to the approach from [php-dot-array](https://github.com/RaggiTech/php-dot-array) repository, I think it should do following works:

- Add tests with PHPUnit.
- Add GitHub Workflow Action to enable this CI integration.

Once this issue is accepted, I would be happy to work on this :).

**Comment by RaggiTech** [comment]
@peter279k it gonna be great if u worked on it :)
